version: '3.8'

services:
  app:
    build: .
    container_name: pdf_chat_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: ["streamlit", "run", "app.py"]
